### ISSUE TITLE
Add support for https://www.schoolholidayseurope.eu

### ISSUE THREAD

**Issue by elRadix** [rt400/School-Vacation#1]
Would be great if you can  add all [Europe school holidays](https://www.schoolholidayseurope.eu) to have greater usage of your component as its now available in HACS.

I am particular interested in belgium ;-)
https://www.schoolholidayseurope.eu/school-holidays-belgium/

**Comment by rt400** [comment]
Hi
The component was originally built for Israel only.
I will try to make it more dynamic for the rest of the countries.
It will take some time.

**Comment by pijiulaoshi** [comment]
I have managed to adapt the component a bit, to cater for the holidays I want to see (and translated some of the Hebrew :) ). I may be doing something wrong, but it seems like the dates added in the json file only work for one day. If I add holidays that stretch over the course of a week, it only detects the first day of the holiday.

Anyways, with a small change, this component could work for anyone, as @elRadix requested. All the users need to do is create their own json file.

Thanks for the great work on this component!

**Comment by rt400** [comment]
Hi @pijiulaoshi , The code works in a simple way, it takes from the JSON file the start date and the end date and then it checks if it is in range, so if we set it an end date greater than 24 hours it will work without issue it is also valid for a week.
I might need to publish a version without Hebrew and fit any JSON file and anyone can create the file for it.
